import org.specs2.mutable._
import org.specs2.runner._
import org.junit.runner._

import play.api.test._
import play.api.test.Helpers._

/**
 * add your integration spec here.
 * An integration test will fire up a whole play application in a real (or headless) browser
 */
@RunWith(classOf[JUnitRunner])
class IntegrationSpec extends Specification {

  /*
  "Application" should {

    "work from within a browser" in new WithBrowser {

      browser.goTo("http://localhost:" + port)

      browser.pageSource must contain("users")
    }
  }
  */
}
/*
// Test failure:

$ sbt test
[info] Loading project definition from /home/johnreed/Desktop/Apps/play-heroku-seed/project
[info] Set current project to play-heroku-seed (in build file:/home/johnreed/Desktop/Apps/play-heroku-seed/)
[info] Compiling 11 Scala sources and 1 Java source to /home/johnreed/Desktop/Apps/play-heroku-seed/target/scala-2.11/classes...
[info] Compiling 2 Scala sources to /home/johnreed/Desktop/Apps/play-heroku-seed/target/scala-2.11/test-classes...
[info] IntegrationSpec
[info]
[info] Application should
[info] ! work from within a browser
[error]    WebDriverException: : com.gargoylesoftware.htmlunit.ScriptException: Error: Bootstrap's JavaScript requires jQuery (https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js#6)
[error] Build info: version: '2.39.0', revision: '14fa800511cc5d66d426e08b0b2ab926c7ed7398', time: '2013-12-16 13:18:38'
[error] System info: host: 'johnreed-Galago-UltraPro', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.2.0-27-generic', java.version: '1.7.0_79'
[error] Driver info: driver.version: HtmlUnitDriver  (HtmlUnitDriver.java:484)
[error] org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:484)
[error] org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:463)
[error] org.fluentlenium.core.Fluent.goTo(Fluent.java:336)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1.delayedEndpoint$IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1$1(IntegrationSpec.scala:19)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1$delayedInit$body.apply(IntegrationSpec.scala:17)
[error] play.api.test.WithBrowser$$anonfun$around$3.apply(Specs.scala:65)
[error] play.api.test.WithBrowser$$anonfun$around$3.apply(Specs.scala:65)
[error] play.api.test.PlayRunners$class.running(Helpers.scala:63)
[error] play.api.test.Helpers$.running(Helpers.scala:403)
[error] play.api.test.WithBrowser.around(Specs.scala:65)
[error] play.api.test.WithBrowser.delayedInit(Specs.scala:48)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1.<init>(IntegrationSpec.scala:17)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1.apply(IntegrationSpec.scala:17)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1.apply(IntegrationSpec.scala:17)
[error] com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:684)
[error] net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:602)
[error] net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:507)
[error] com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:570)
[error] com.gargoylesoftware.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:1062)
[error] com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:409)
[error] com.gargoylesoftware.htmlunit.html.HtmlScript$3.execute(HtmlScript.java:266)
[error] com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:286)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:683)
[error] org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:642)
[error] org.cyberneko.html.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1170)
[error] org.cyberneko.html.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1072)
[error] org.cyberneko.html.filters.DefaultFilter.endElement(DefaultFilter.java:206)
[error] org.cyberneko.html.filters.NamespaceBinder.endElement(NamespaceBinder.java:330)
[error] org.cyberneko.html.HTMLScanner$ContentScanner.scanEndElement(HTMLScanner.java:3116)
[error] org.cyberneko.html.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2083)
[error] org.cyberneko.html.HTMLScanner.scanDocument(HTMLScanner.java:918)
[error] org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:499)
[error] org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:452)
[error] org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.parse(HTMLParser.java:899)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser.parse(HTMLParser.java:242)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser.parseHtml(HTMLParser.java:188)
[error] com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:268)
[error] com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:156)
[error] com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:437)
[error] com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:311)
[error] com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:376)
[error] org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:474)
[error] org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:463)
[error] org.fluentlenium.core.Fluent.goTo(Fluent.java:336)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1.delayedEndpoint$IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1$1(IntegrationSpec.scala:19)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1$delayedInit$body.apply(IntegrationSpec.scala:17)
[error] play.api.test.WithBrowser$$anonfun$around$3.apply(Specs.scala:65)
[error] play.api.test.WithBrowser$$anonfun$around$3.apply(Specs.scala:65)
[error] play.api.test.PlayRunners$class.running(Helpers.scala:63)
[error] play.api.test.Helpers$.running(Helpers.scala:403)
[error] play.api.test.WithBrowser.around(Specs.scala:65)
[error] play.api.test.WithBrowser.delayedInit(Specs.scala:48)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1.<init>(IntegrationSpec.scala:17)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1.apply(IntegrationSpec.scala:17)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1.apply(IntegrationSpec.scala:17)
[error] net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1006)
[error] net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:798)
[error] net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:105)
[error] net.sourceforge.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
[error] com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:309)
[error] net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3031)
[error] net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.exec(InterpretedFunction.java:115)
[error] com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$3.doRun(JavaScriptEngine.java:561)
[error] com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:669)
[error] net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:602)
[error] net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:507)
[error] com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:570)
[error] com.gargoylesoftware.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:1062)
[error] com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:409)
[error] com.gargoylesoftware.htmlunit.html.HtmlScript$3.execute(HtmlScript.java:266)
[error] com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:286)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:683)
[error] org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:642)
[error] org.cyberneko.html.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1170)
[error] org.cyberneko.html.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1072)
[error] org.cyberneko.html.filters.DefaultFilter.endElement(DefaultFilter.java:206)
[error] org.cyberneko.html.filters.NamespaceBinder.endElement(NamespaceBinder.java:330)
[error] org.cyberneko.html.HTMLScanner$ContentScanner.scanEndElement(HTMLScanner.java:3116)
[error] org.cyberneko.html.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2083)
[error] org.cyberneko.html.HTMLScanner.scanDocument(HTMLScanner.java:918)
[error] org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:499)
[error] org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:452)
[error] org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.parse(HTMLParser.java:899)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser.parse(HTMLParser.java:242)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser.parseHtml(HTMLParser.java:188)
[error] com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:268)
[error] com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:156)
[error] com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:437)
[error] com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:311)
[error] com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:376)
[error] org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:474)
[error] org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:463)
[error] org.fluentlenium.core.Fluent.goTo(Fluent.java:336)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1.delayedEndpoint$IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1$1(IntegrationSpec.scala:19)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1$delayedInit$body.apply(IntegrationSpec.scala:17)
[error] play.api.test.WithBrowser$$anonfun$around$3.apply(Specs.scala:65)
[error] play.api.test.WithBrowser$$anonfun$around$3.apply(Specs.scala:65)
[error] play.api.test.PlayRunners$class.running(Helpers.scala:63)
[error] play.api.test.Helpers$.running(Helpers.scala:403)
[error] play.api.test.WithBrowser.around(Specs.scala:65)
[error] play.api.test.WithBrowser.delayedInit(Specs.scala:48)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1.<init>(IntegrationSpec.scala:17)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1.apply(IntegrationSpec.scala:17)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1.apply(IntegrationSpec.scala:17)
[error]
[error] Caused by com.gargoylesoftware.htmlunit.ScriptException: Error: Bootstrap's JavaScript requires jQuery (https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js#6)
[error] com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:684)
[error] net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:602)
[error] net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:507)
[error] com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:570)
[error] com.gargoylesoftware.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:1062)
[error] com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:409)
[error] com.gargoylesoftware.htmlunit.html.HtmlScript$3.execute(HtmlScript.java:266)
[error] com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:286)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:683)
[error] org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:642)
[error] org.cyberneko.html.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1170)
[error] org.cyberneko.html.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1072)
[error] org.cyberneko.html.filters.DefaultFilter.endElement(DefaultFilter.java:206)
[error] org.cyberneko.html.filters.NamespaceBinder.endElement(NamespaceBinder.java:330)
[error] org.cyberneko.html.HTMLScanner$ContentScanner.scanEndElement(HTMLScanner.java:3116)
[error] org.cyberneko.html.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2083)
[error] org.cyberneko.html.HTMLScanner.scanDocument(HTMLScanner.java:918)
[error] org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:499)
[error] org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:452)
[error] org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.parse(HTMLParser.java:899)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser.parse(HTMLParser.java:242)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser.parseHtml(HTMLParser.java:188)
[error] com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:268)
[error] com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:156)
[error] com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:437)
[error] com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:311)
[error] com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:376)
[error] org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:474)
[error] org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:463)
[error] org.fluentlenium.core.Fluent.goTo(Fluent.java:336)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1.delayedEndpoint$IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1$1(IntegrationSpec.scala:19)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1$delayedInit$body.apply(IntegrationSpec.scala:17)
[error] play.api.test.WithBrowser$$anonfun$around$3.apply(Specs.scala:65)
[error] play.api.test.WithBrowser$$anonfun$around$3.apply(Specs.scala:65)
[error] play.api.test.PlayRunners$class.running(Helpers.scala:63)
[error] play.api.test.Helpers$.running(Helpers.scala:403)
[error] play.api.test.WithBrowser.around(Specs.scala:65)
[error] play.api.test.WithBrowser.delayedInit(Specs.scala:48)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1.<init>(IntegrationSpec.scala:17)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1.apply(IntegrationSpec.scala:17)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1.apply(IntegrationSpec.scala:17)
[error]
[error] Caused by net.sourceforge.htmlunit.corejs.javascript.JavaScriptException: Error: Bootstrap's JavaScript requires jQuery (https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js#6)
[error] net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1006)
[error] net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:798)
[error] net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:105)
[error] net.sourceforge.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
[error] com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:309)
[error] net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3031)
[error] net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.exec(InterpretedFunction.java:115)
[error] com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$3.doRun(JavaScriptEngine.java:561)
[error] com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:669)
[error] net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:602)
[error] net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:507)
[error] com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:570)
[error] com.gargoylesoftware.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:1062)
[error] com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:409)
[error] com.gargoylesoftware.htmlunit.html.HtmlScript$3.execute(HtmlScript.java:266)
[error] com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:286)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:683)
[error] org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:642)
[error] org.cyberneko.html.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1170)
[error] org.cyberneko.html.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1072)
[error] org.cyberneko.html.filters.DefaultFilter.endElement(DefaultFilter.java:206)
[error] org.cyberneko.html.filters.NamespaceBinder.endElement(NamespaceBinder.java:330)
[error] org.cyberneko.html.HTMLScanner$ContentScanner.scanEndElement(HTMLScanner.java:3116)
[error] org.cyberneko.html.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2083)
[error] org.cyberneko.html.HTMLScanner.scanDocument(HTMLScanner.java:918)
[error] org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:499)
[error] org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:452)
[error] org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.parse(HTMLParser.java:899)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser.parse(HTMLParser.java:242)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser.parseHtml(HTMLParser.java:188)
[error] com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:268)
[error] com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:156)
[error] com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:437)
[error] com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:311)
[error] com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:376)
[error] org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:474)
[error] org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:463)
[error] org.fluentlenium.core.Fluent.goTo(Fluent.java:336)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1.delayedEndpoint$IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1$1(IntegrationSpec.scala:19)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1$delayedInit$body.apply(IntegrationSpec.scala:17)
[error] play.api.test.WithBrowser$$anonfun$around$3.apply(Specs.scala:65)
[error] play.api.test.WithBrowser$$anonfun$around$3.apply(Specs.scala:65)
[error] play.api.test.PlayRunners$class.running(Helpers.scala:63)
[error] play.api.test.Helpers$.running(Helpers.scala:403)
[error] play.api.test.WithBrowser.around(Specs.scala:65)
[error] play.api.test.WithBrowser.delayedInit(Specs.scala:48)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1.<init>(IntegrationSpec.scala:17)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1.apply(IntegrationSpec.scala:17)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1.apply(IntegrationSpec.scala:17)
[info]
[info]
[info] Total for specification IntegrationSpec
[info] Finished in 7 seconds, 470 ms
[info] 1 example, 0 failure, 1 error
[info] ApplicationSpec
[info]
[info] Application should
[info] + send 404 on a bad request
[info] ! render the index page
[error]    SQLException: : Attempting to obtain a connection from a pool that has already been shutdown.
[error] Stack trace of location where pool was shutdown follows:
[error]  java.lang.Thread.getStackTrace(Thread.java:1589)
[error]  com.jolbox.bonecp.BoneCP.captureStackTrace(BoneCP.java:572)
[error]  com.jolbox.bonecp.BoneCP.shutdown(BoneCP.java:161)
[error]  com.jolbox.bonecp.BoneCPDataSource.close(BoneCPDataSource.java:143)
[error]  play.api.db.BoneCPApi.shutdownPool(DB.scala:423)
[error]  play.api.db.BoneCPPlugin$$anonfun$onStop$1.apply(DB.scala:260)
[error]  play.api.db.BoneCPPlugin$$anonfun$onStop$1.apply(DB.scala:258)
[error]  scala.collection.immutable.List.foreach(List.scala:381)
[error]  play.api.db.BoneCPPlugin.onStop(DB.scala:258)
[error]  play.api.Play$$anonfun$stop$1$$anonfun$apply$1$$anonfun$apply$mcV$sp$2.apply(Play.scala:108)
[error]  play.api.Play$$anonfun$stop$1$$anonfun$apply$1$$anonfun$apply$mcV$sp$2.apply(Play.scala:107)
[error]  scala.collection.immutable.List.foreach(List.scala:381)
[error]  play.api.Play$$anonfun$stop$1$$anonfun$apply$1.apply$mcV$sp(Play.scala:107)
[error]  play.api.Play$$anonfun$stop$1$$anonfun$apply$1.apply(Play.scala:107)
[error]  play.api.Play$$anonfun$stop$1$$anonfun$apply$1.apply(Play.scala:107)
[error]  play.utils.Threads$.withContextClassLoader(Threads.scala:21)
[error]  play.api.Play$$anonfun$stop$1.apply(Play.scala:106)
[error]  play.api.Play$$anonfun$stop$1.apply(Play.scala:105)
[error]  scala.Option.map(Option.scala:146)
[error]  play.api.Play$.stop(Play.scala:105)
[error]  play.core.server.NettyServer.stop(NettyServer.scala:158)
[error]  play.api.test.TestServer.stop(Selenium.scala:161)
[error]  play.api.test.PlayRunners$class.running(Helpers.scala:65)
[error]  play.api.test.Helpers$.running(Helpers.scala:403)
[error]  play.api.test.WithBrowser.around(Specs.scala:65)
[error]  org.specs2.mutable.Around$$anonfun$delayedInit$1.apply(Around.scala:13)
[error]  org.specs2.mutable.Around$$anonfun$delayedInit$1.apply(Around.scala:13)
[error]  org.specs2.execute.ResultExecution$class.effectively(ResultExecution.scala:38)
[error]  org.specs2.execute.ResultExecution$.effectively(ResultExecution.scala:116)
[error]  org.specs2.mutable.Around$class.delayedInit(Around.scala:13)
[error]  play.api.test.WithBrowser.delayedInit(Specs.scala:48)
[error]  IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1.<init>(IntegrationSpec.scala:17)
[error]  IntegrationSpec$$anonfun$1$$anonfun$apply$1.apply(IntegrationSpec.scala:17)
[error]  IntegrationSpec$$anonfun$1$$anonfun$apply$1.apply(IntegrationSpec.scala:17)
[error]  org.specs2.matcher.Scope$$anon$3.asResult(ThrownExpectations.scala:120)
[error]  org.specs2.execute.AsResult$.apply(Result.scala:253)
[error]  org.specs2.specification.Example$$anonfun$apply$1.apply(Fragment.scala:209)
[error]  org.specs2.specification.Example$$anonfun$apply$1.apply(Fragment.scala:209)
[error]  org.specs2.specification.Example.execute(Fragment.scala:176)
[error]  org.specs2.specification.FragmentExecution$$anonfun$1.apply(FragmentExecution.scala:46)
[error]  org.specs2.specification.FragmentExecution$$anonfun$1.apply(FragmentExecution.scala:46)
[error]  org.specs2.execute.ResultExecution$class.execute(ResultExecution.scala:22)
[error]  org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:116)
[error]  org.specs2.specification.FragmentExecution$class.executeBody(FragmentExecution.scala:28)
[error]  org.specs2.reporter.SbtConsoleReporter.executeBody(SbtReporter.scala:20)
[error]  org.specs2.specification.FragmentExecution$class.execute(FragmentExecution.scala:46)
[error]  org.specs2.reporter.SbtConsoleReporter.execute(SbtReporter.scala:20)
[error]  org.specs2.specification.FragmentExecution$$anonfun$executeFragment$1$$anonfun$apply$1.apply(FragmentExecution.scala:35)
[error]  org.specs2.specification.FragmentExecution$$anonfun$executeFragment$1$$anonfun$apply$1.apply(FragmentExecution.scala:35)
[error]  org.specs2.control.Exceptions$class.catchAllOr(Exceptions.scala:54)
[error]  org.specs2.control.Exceptions$.catchAllOr(Exceptions.scala:109)
[error]  org.specs2.specification.FragmentExecution$$anonfun$executeFragment$1.apply(FragmentExecution.scala:35)
[error]  org.specs2.specification.FragmentExecution$$anonfun$executeFragment$1.apply(FragmentExecution.scala:35)
[error]  org.specs2.reporter.DefaultExecutionStrategy$$anonfun$executeSequentially$1.apply(ExecutionStrategy.scala:104)
[error]  org.specs2.reporter.DefaultExecutionStrategy$$anonfun$executeSequentially$1.apply(ExecutionStrategy.scala:104)
[error]  scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error]  scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error]  scala.collection.immutable.List.foreach(List.scala:381)
[error]  scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[error]  scala.collection.immutable.List.map(List.scala:285)
[error]  org.specs2.reporter.DefaultExecutionStrategy$class.executeSequentially(ExecutionStrategy.scala:104)
[error]  org.specs2.reporter.SbtConsoleReporter.executeSequentially(SbtReporter.scala:20)
[error]  org.specs2.reporter.DefaultExecutionStrategy$class.executeSequence(ExecutionStrategy.scala:98)
[error]  org.specs2.reporter.SbtConsoleReporter.executeSequence(SbtReporter.scala:20)
[error]  org.specs2.reporter.DefaultExecutionStrategy$$anonfun$execute$1$$anonfun$2.apply(ExecutionStrategy.scala:43)
[error]  org.specs2.reporter.DefaultExecutionStrategy$$anonfun$execute$1$$anonfun$2.apply(ExecutionStrategy.scala:41)
[error]  scala.collection.immutable.Stream.foldLeft(Stream.scala:610)
[error]  org.specs2.reporter.DefaultExecutionStrategy$$anonfun$execute$1.apply(ExecutionStrategy.scala:41)
[error]  org.specs2.reporter.DefaultExecutionStrategy$$anonfun$execute$1.apply(ExecutionStrategy.scala:38)
[error]  scalaz.syntax.IdOps$class.$bar$greater(IdOps.scala:15)
[error]  scalaz.syntax.ToIdOps$$anon$1.$bar$greater(IdOps.scala:82)
[error]  org.specs2.reporter.AllExporting$class.report(AllExporting.scala:17)
[error]  org.specs2.reporter.SbtConsoleReporter.report(SbtReporter.scala:20)
[error]  org.specs2.runner.SbtRunner.org$specs2$runner$SbtRunner$$specificationRun(SbtRunner.scala:75)
[error]  org.specs2.runner.SbtRunner$$anonfun$newTask$1$$anon$5.execute(SbtRunner.scala:59)
[error]  sbt.ForkMain$Run$2.call(ForkMain.java:294)
[error]  sbt.ForkMain$Run$2.call(ForkMain.java:284)
[error]  java.util.concurrent.FutureTask.run(FutureTask.java:262)
[error]  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[error]  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[error]  java.lang.Thread.run(Thread.java:745)
[error]   (AbstractConnectionStrategy.java:52)
[error] com.jolbox.bonecp.AbstractConnectionStrategy.preConnection(AbstractConnectionStrategy.java:52)
[error] com.jolbox.bonecp.AbstractConnectionStrategy.getConnection(AbstractConnectionStrategy.java:88)
[error] com.jolbox.bonecp.BoneCP.getConnection(BoneCP.java:553)
[error] com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:131)
[error] models.Users$$anonfun$all$1.apply(Users.scala:21)
[error] models.Users$$anonfun$all$1.apply(Users.scala:20)
[error] models.Users$.all(Users.scala:20)
[error] controllers.Application$$anonfun$index$1.apply(Application.scala:17)
[error] controllers.Application$$anonfun$index$1.apply(Application.scala:17)
[error] play.api.mvc.ActionBuilder$$anonfun$apply$17.apply(Action.scala:464)
[error] play.api.mvc.ActionBuilder$$anonfun$apply$17.apply(Action.scala:464)
[error] play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:433)
[error] play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:432)
[error] play.api.mvc.Action$.invokeBlock(Action.scala:556)
[error] play.api.mvc.Action$.invokeBlock(Action.scala:555)
[error] play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:518)
[error] play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
[error] play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
[error] play.utils.Threads$.withContextClassLoader(Threads.scala:21)
[error] play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129)
[error] play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128)
[error] play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128)
[error] play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121)
[error] play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705)
[error] play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705)
[error] akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
[error] akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
[info]
[info]
[info] Total for specification ApplicationSpec
[info] Finished in 2 seconds, 811 ms
[info] 2 examples, 0 failure, 1 error
[error] Error: Total 3, Failed 0, Errors 2, Passed 1
[error] Error during tests:
[error]         ApplicationSpec
[error]         IntegrationSpec
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 27 s, completed Jul 21, 2016 12:50:45 AM
johnreed@johnreed-Galago-UltraPro:~/Desktop/Apps/play-heroku-seed$ sbt test
[info] Loading project definition from /home/johnreed/Desktop/Apps/play-heroku-seed/project
[info] Set current project to play-heroku-seed (in build file:/home/johnreed/Desktop/Apps/play-heroku-seed/)
[info] Compiling 2 Scala sources to /home/johnreed/Desktop/Apps/play-heroku-seed/target/scala-2.11/test-classes...
[info] IntegrationSpec
[info]
[info] Application should
[info] ! work from within a browser
[error]    WebDriverException: : com.gargoylesoftware.htmlunit.ScriptException: Error: Bootstrap's JavaScript requires jQuery (https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js#6)
[error] Build info: version: '2.39.0', revision: '14fa800511cc5d66d426e08b0b2ab926c7ed7398', time: '2013-12-16 13:18:38'
[error] System info: host: 'johnreed-Galago-UltraPro', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.2.0-27-generic', java.version: '1.7.0_79'
[error] Driver info: driver.version: HtmlUnitDriver  (HtmlUnitDriver.java:484)
[error] org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:484)
[error] org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:463)
[error] org.fluentlenium.core.Fluent.goTo(Fluent.java:336)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1.delayedEndpoint$IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1$1(IntegrationSpec.scala:19)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1$delayedInit$body.apply(IntegrationSpec.scala:17)
[error] play.api.test.WithBrowser$$anonfun$around$3.apply(Specs.scala:65)
[error] play.api.test.WithBrowser$$anonfun$around$3.apply(Specs.scala:65)
[error] play.api.test.PlayRunners$class.running(Helpers.scala:63)
[error] play.api.test.Helpers$.running(Helpers.scala:403)
[error] play.api.test.WithBrowser.around(Specs.scala:65)
[error] play.api.test.WithBrowser.delayedInit(Specs.scala:48)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1.<init>(IntegrationSpec.scala:17)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1.apply(IntegrationSpec.scala:17)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1.apply(IntegrationSpec.scala:17)
[error] com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:684)
[error] net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:602)
[error] net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:507)
[error] com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:570)
[error] com.gargoylesoftware.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:1062)
[error] com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:409)
[error] com.gargoylesoftware.htmlunit.html.HtmlScript$3.execute(HtmlScript.java:266)
[error] com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:286)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:683)
[error] org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:642)
[error] org.cyberneko.html.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1170)
[error] org.cyberneko.html.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1072)
[error] org.cyberneko.html.filters.DefaultFilter.endElement(DefaultFilter.java:206)
[error] org.cyberneko.html.filters.NamespaceBinder.endElement(NamespaceBinder.java:330)
[error] org.cyberneko.html.HTMLScanner$ContentScanner.scanEndElement(HTMLScanner.java:3116)
[error] org.cyberneko.html.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2083)
[error] org.cyberneko.html.HTMLScanner.scanDocument(HTMLScanner.java:918)
[error] org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:499)
[error] org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:452)
[error] org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.parse(HTMLParser.java:899)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser.parse(HTMLParser.java:242)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser.parseHtml(HTMLParser.java:188)
[error] com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:268)
[error] com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:156)
[error] com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:437)
[error] com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:311)
[error] com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:376)
[error] org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:474)
[error] org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:463)
[error] org.fluentlenium.core.Fluent.goTo(Fluent.java:336)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1.delayedEndpoint$IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1$1(IntegrationSpec.scala:19)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1$delayedInit$body.apply(IntegrationSpec.scala:17)
[error] play.api.test.WithBrowser$$anonfun$around$3.apply(Specs.scala:65)
[error] play.api.test.WithBrowser$$anonfun$around$3.apply(Specs.scala:65)
[error] play.api.test.PlayRunners$class.running(Helpers.scala:63)
[error] play.api.test.Helpers$.running(Helpers.scala:403)
[error] play.api.test.WithBrowser.around(Specs.scala:65)
[error] play.api.test.WithBrowser.delayedInit(Specs.scala:48)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1.<init>(IntegrationSpec.scala:17)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1.apply(IntegrationSpec.scala:17)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1.apply(IntegrationSpec.scala:17)
[error] net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1006)
[error] net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:798)
[error] net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:105)
[error] net.sourceforge.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
[error] com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:309)
[error] net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3031)
[error] net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.exec(InterpretedFunction.java:115)
[error] com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$3.doRun(JavaScriptEngine.java:561)
[error] com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:669)
[error] net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:602)
[error] net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:507)
[error] com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:570)
[error] com.gargoylesoftware.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:1062)
[error] com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:409)
[error] com.gargoylesoftware.htmlunit.html.HtmlScript$3.execute(HtmlScript.java:266)
[error] com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:286)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:683)
[error] org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:642)
[error] org.cyberneko.html.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1170)
[error] org.cyberneko.html.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1072)
[error] org.cyberneko.html.filters.DefaultFilter.endElement(DefaultFilter.java:206)
[error] org.cyberneko.html.filters.NamespaceBinder.endElement(NamespaceBinder.java:330)
[error] org.cyberneko.html.HTMLScanner$ContentScanner.scanEndElement(HTMLScanner.java:3116)
[error] org.cyberneko.html.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2083)
[error] org.cyberneko.html.HTMLScanner.scanDocument(HTMLScanner.java:918)
[error] org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:499)
[error] org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:452)
[error] org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.parse(HTMLParser.java:899)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser.parse(HTMLParser.java:242)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser.parseHtml(HTMLParser.java:188)
[error] com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:268)
[error] com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:156)
[error] com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:437)
[error] com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:311)
[error] com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:376)
[error] org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:474)
[error] org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:463)
[error] org.fluentlenium.core.Fluent.goTo(Fluent.java:336)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1.delayedEndpoint$IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1$1(IntegrationSpec.scala:19)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1$delayedInit$body.apply(IntegrationSpec.scala:17)
[error] play.api.test.WithBrowser$$anonfun$around$3.apply(Specs.scala:65)
[error] play.api.test.WithBrowser$$anonfun$around$3.apply(Specs.scala:65)
[error] play.api.test.PlayRunners$class.running(Helpers.scala:63)
[error] play.api.test.Helpers$.running(Helpers.scala:403)
[error] play.api.test.WithBrowser.around(Specs.scala:65)
[error] play.api.test.WithBrowser.delayedInit(Specs.scala:48)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1.<init>(IntegrationSpec.scala:17)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1.apply(IntegrationSpec.scala:17)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1.apply(IntegrationSpec.scala:17)
[error]
[error] Caused by com.gargoylesoftware.htmlunit.ScriptException: Error: Bootstrap's JavaScript requires jQuery (https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js#6)
[error] com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:684)
[error] net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:602)
[error] net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:507)
[error] com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:570)
[error] com.gargoylesoftware.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:1062)
[error] com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:409)
[error] com.gargoylesoftware.htmlunit.html.HtmlScript$3.execute(HtmlScript.java:266)
[error] com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:286)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:683)
[error] org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:642)
[error] org.cyberneko.html.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1170)
[error] org.cyberneko.html.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1072)
[error] org.cyberneko.html.filters.DefaultFilter.endElement(DefaultFilter.java:206)
[error] org.cyberneko.html.filters.NamespaceBinder.endElement(NamespaceBinder.java:330)
[error] org.cyberneko.html.HTMLScanner$ContentScanner.scanEndElement(HTMLScanner.java:3116)
[error] org.cyberneko.html.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2083)
[error] org.cyberneko.html.HTMLScanner.scanDocument(HTMLScanner.java:918)
[error] org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:499)
[error] org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:452)
[error] org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.parse(HTMLParser.java:899)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser.parse(HTMLParser.java:242)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser.parseHtml(HTMLParser.java:188)
[error] com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:268)
[error] com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:156)
[error] com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:437)
[error] com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:311)
[error] com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:376)
[error] org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:474)
[error] org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:463)
[error] org.fluentlenium.core.Fluent.goTo(Fluent.java:336)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1.delayedEndpoint$IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1$1(IntegrationSpec.scala:19)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1$delayedInit$body.apply(IntegrationSpec.scala:17)
[error] play.api.test.WithBrowser$$anonfun$around$3.apply(Specs.scala:65)
[error] play.api.test.WithBrowser$$anonfun$around$3.apply(Specs.scala:65)
[error] play.api.test.PlayRunners$class.running(Helpers.scala:63)
[error] play.api.test.Helpers$.running(Helpers.scala:403)
[error] play.api.test.WithBrowser.around(Specs.scala:65)
[error] play.api.test.WithBrowser.delayedInit(Specs.scala:48)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1.<init>(IntegrationSpec.scala:17)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1.apply(IntegrationSpec.scala:17)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1.apply(IntegrationSpec.scala:17)
[error]
[error] Caused by net.sourceforge.htmlunit.corejs.javascript.JavaScriptException: Error: Bootstrap's JavaScript requires jQuery (https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js#6)
[error] net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1006)
[error] net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:798)
[error] net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:105)
[error] net.sourceforge.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
[error] com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:309)
[error] net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3031)
[error] net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.exec(InterpretedFunction.java:115)
[error] com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$3.doRun(JavaScriptEngine.java:561)
[error] com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:669)
[error] net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:602)
[error] net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:507)
[error] com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:570)
[error] com.gargoylesoftware.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:1062)
[error] com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:409)
[error] com.gargoylesoftware.htmlunit.html.HtmlScript$3.execute(HtmlScript.java:266)
[error] com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:286)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:683)
[error] org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:642)
[error] org.cyberneko.html.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1170)
[error] org.cyberneko.html.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1072)
[error] org.cyberneko.html.filters.DefaultFilter.endElement(DefaultFilter.java:206)
[error] org.cyberneko.html.filters.NamespaceBinder.endElement(NamespaceBinder.java:330)
[error] org.cyberneko.html.HTMLScanner$ContentScanner.scanEndElement(HTMLScanner.java:3116)
[error] org.cyberneko.html.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2083)
[error] org.cyberneko.html.HTMLScanner.scanDocument(HTMLScanner.java:918)
[error] org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:499)
[error] org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:452)
[error] org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.parse(HTMLParser.java:899)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser.parse(HTMLParser.java:242)
[error] com.gargoylesoftware.htmlunit.html.HTMLParser.parseHtml(HTMLParser.java:188)
[error] com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:268)
[error] com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:156)
[error] com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:437)
[error] com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:311)
[error] com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:376)
[error] org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:474)
[error] org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:463)
[error] org.fluentlenium.core.Fluent.goTo(Fluent.java:336)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1.delayedEndpoint$IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1$1(IntegrationSpec.scala:19)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1$delayedInit$body.apply(IntegrationSpec.scala:17)
[error] play.api.test.WithBrowser$$anonfun$around$3.apply(Specs.scala:65)
[error] play.api.test.WithBrowser$$anonfun$around$3.apply(Specs.scala:65)
[error] play.api.test.PlayRunners$class.running(Helpers.scala:63)
[error] play.api.test.Helpers$.running(Helpers.scala:403)
[error] play.api.test.WithBrowser.around(Specs.scala:65)
[error] play.api.test.WithBrowser.delayedInit(Specs.scala:48)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1.<init>(IntegrationSpec.scala:17)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1.apply(IntegrationSpec.scala:17)
[error] IntegrationSpec$$anonfun$1$$anonfun$apply$1.apply(IntegrationSpec.scala:17)
[info]
[info]
[info] Total for specification IntegrationSpec
[info] Finished in 6 seconds, 423 ms
[info] 1 example, 0 failure, 1 error
[info] ApplicationSpec
[info]
[info] Application should
[info] ! render the index page
[error]    SQLException: : Attempting to obtain a connection from a pool that has already been shutdown.
[error] Stack trace of location where pool was shutdown follows:
[error]  java.lang.Thread.getStackTrace(Thread.java:1589)
[error]  com.jolbox.bonecp.BoneCP.captureStackTrace(BoneCP.java:572)
[error]  com.jolbox.bonecp.BoneCP.shutdown(BoneCP.java:161)
[error]  com.jolbox.bonecp.BoneCPDataSource.close(BoneCPDataSource.java:143)
[error]  play.api.db.BoneCPApi.shutdownPool(DB.scala:423)
[error]  play.api.db.BoneCPPlugin$$anonfun$onStop$1.apply(DB.scala:260)
[error]  play.api.db.BoneCPPlugin$$anonfun$onStop$1.apply(DB.scala:258)
[error]  scala.collection.immutable.List.foreach(List.scala:381)
[error]  play.api.db.BoneCPPlugin.onStop(DB.scala:258)
[error]  play.api.Play$$anonfun$stop$1$$anonfun$apply$1$$anonfun$apply$mcV$sp$2.apply(Play.scala:108)
[error]  play.api.Play$$anonfun$stop$1$$anonfun$apply$1$$anonfun$apply$mcV$sp$2.apply(Play.scala:107)
[error]  scala.collection.immutable.List.foreach(List.scala:381)
[error]  play.api.Play$$anonfun$stop$1$$anonfun$apply$1.apply$mcV$sp(Play.scala:107)
[error]  play.api.Play$$anonfun$stop$1$$anonfun$apply$1.apply(Play.scala:107)
[error]  play.api.Play$$anonfun$stop$1$$anonfun$apply$1.apply(Play.scala:107)
[error]  play.utils.Threads$.withContextClassLoader(Threads.scala:21)
[error]  play.api.Play$$anonfun$stop$1.apply(Play.scala:106)
[error]  play.api.Play$$anonfun$stop$1.apply(Play.scala:105)
[error]  scala.Option.map(Option.scala:146)
[error]  play.api.Play$.stop(Play.scala:105)
[error]  play.core.server.NettyServer.stop(NettyServer.scala:158)
[error]  play.api.test.TestServer.stop(Selenium.scala:161)
[error]  play.api.test.PlayRunners$class.running(Helpers.scala:65)
[error]  play.api.test.Helpers$.running(Helpers.scala:403)
[error]  play.api.test.WithBrowser.around(Specs.scala:65)
[error]  org.specs2.mutable.Around$$anonfun$delayedInit$1.apply(Around.scala:13)
[error]  org.specs2.mutable.Around$$anonfun$delayedInit$1.apply(Around.scala:13)
[error]  org.specs2.execute.ResultExecution$class.effectively(ResultExecution.scala:38)
[error]  org.specs2.execute.ResultExecution$.effectively(ResultExecution.scala:116)
[error]  org.specs2.mutable.Around$class.delayedInit(Around.scala:13)
[error]  play.api.test.WithBrowser.delayedInit(Specs.scala:48)
[error]  IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1.<init>(IntegrationSpec.scala:17)
[error]  IntegrationSpec$$anonfun$1$$anonfun$apply$1.apply(IntegrationSpec.scala:17)
[error]  IntegrationSpec$$anonfun$1$$anonfun$apply$1.apply(IntegrationSpec.scala:17)
[error]  org.specs2.matcher.Scope$$anon$3.asResult(ThrownExpectations.scala:120)
[error]  org.specs2.execute.AsResult$.apply(Result.scala:253)
[error]  org.specs2.specification.Example$$anonfun$apply$1.apply(Fragment.scala:209)
[error]  org.specs2.specification.Example$$anonfun$apply$1.apply(Fragment.scala:209)
[error]  org.specs2.specification.Example.execute(Fragment.scala:176)
[error]  org.specs2.specification.FragmentExecution$$anonfun$1.apply(FragmentExecution.scala:46)
[error]  org.specs2.specification.FragmentExecution$$anonfun$1.apply(FragmentExecution.scala:46)
[error]  org.specs2.execute.ResultExecution$class.execute(ResultExecution.scala:22)
[error]  org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:116)
[error]  org.specs2.specification.FragmentExecution$class.executeBody(FragmentExecution.scala:28)
[error]  org.specs2.reporter.SbtConsoleReporter.executeBody(SbtReporter.scala:20)
[error]  org.specs2.specification.FragmentExecution$class.execute(FragmentExecution.scala:46)
[error]  org.specs2.reporter.SbtConsoleReporter.execute(SbtReporter.scala:20)
[error]  org.specs2.specification.FragmentExecution$$anonfun$executeFragment$1$$anonfun$apply$1.apply(FragmentExecution.scala:35)
[error]  org.specs2.specification.FragmentExecution$$anonfun$executeFragment$1$$anonfun$apply$1.apply(FragmentExecution.scala:35)
[error]  org.specs2.control.Exceptions$class.catchAllOr(Exceptions.scala:54)
[error]  org.specs2.control.Exceptions$.catchAllOr(Exceptions.scala:109)
[error]  org.specs2.specification.FragmentExecution$$anonfun$executeFragment$1.apply(FragmentExecution.scala:35)
[error]  org.specs2.specification.FragmentExecution$$anonfun$executeFragment$1.apply(FragmentExecution.scala:35)
[error]  org.specs2.reporter.DefaultExecutionStrategy$$anonfun$executeSequentially$1.apply(ExecutionStrategy.scala:104)
[error]  org.specs2.reporter.DefaultExecutionStrategy$$anonfun$executeSequentially$1.apply(ExecutionStrategy.scala:104)
[error]  scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error]  scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error]  scala.collection.immutable.List.foreach(List.scala:381)
[error]  scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[error]  scala.collection.immutable.List.map(List.scala:285)
[error]  org.specs2.reporter.DefaultExecutionStrategy$class.executeSequentially(ExecutionStrategy.scala:104)
[error]  org.specs2.reporter.SbtConsoleReporter.executeSequentially(SbtReporter.scala:20)
[error]  org.specs2.reporter.DefaultExecutionStrategy$class.executeSequence(ExecutionStrategy.scala:98)
[error]  org.specs2.reporter.SbtConsoleReporter.executeSequence(SbtReporter.scala:20)
[error]  org.specs2.reporter.DefaultExecutionStrategy$$anonfun$execute$1$$anonfun$2.apply(ExecutionStrategy.scala:43)
[error]  org.specs2.reporter.DefaultExecutionStrategy$$anonfun$execute$1$$anonfun$2.apply(ExecutionStrategy.scala:41)
[error]  scala.collection.immutable.Stream.foldLeft(Stream.scala:610)
[error]  org.specs2.reporter.DefaultExecutionStrategy$$anonfun$execute$1.apply(ExecutionStrategy.scala:41)
[error]  org.specs2.reporter.DefaultExecutionStrategy$$anonfun$execute$1.apply(ExecutionStrategy.scala:38)
[error]  scalaz.syntax.IdOps$class.$bar$greater(IdOps.scala:15)
[error]  scalaz.syntax.ToIdOps$$anon$1.$bar$greater(IdOps.scala:82)
[error]  org.specs2.reporter.AllExporting$class.report(AllExporting.scala:17)
[error]  org.specs2.reporter.SbtConsoleReporter.report(SbtReporter.scala:20)
[error]  org.specs2.runner.SbtRunner.org$specs2$runner$SbtRunner$$specificationRun(SbtRunner.scala:75)
[error]  org.specs2.runner.SbtRunner$$anonfun$newTask$1$$anon$5.execute(SbtRunner.scala:59)
[error]  sbt.ForkMain$Run$2.call(ForkMain.java:294)
[error]  sbt.ForkMain$Run$2.call(ForkMain.java:284)
[error]  java.util.concurrent.FutureTask.run(FutureTask.java:262)
[error]  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[error]  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[error]  java.lang.Thread.run(Thread.java:745)
[error]   (AbstractConnectionStrategy.java:52)
[error] com.jolbox.bonecp.AbstractConnectionStrategy.preConnection(AbstractConnectionStrategy.java:52)
[error] com.jolbox.bonecp.AbstractConnectionStrategy.getConnection(AbstractConnectionStrategy.java:88)
[error] com.jolbox.bonecp.BoneCP.getConnection(BoneCP.java:553)
[error] com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:131)
[error] models.Users$$anonfun$all$1.apply(Users.scala:21)
[error] models.Users$$anonfun$all$1.apply(Users.scala:20)
[error] models.Users$.all(Users.scala:20)
[error] controllers.Application$$anonfun$index$1.apply(Application.scala:17)
[error] controllers.Application$$anonfun$index$1.apply(Application.scala:17)
[error] play.api.mvc.ActionBuilder$$anonfun$apply$17.apply(Action.scala:464)
[error] play.api.mvc.ActionBuilder$$anonfun$apply$17.apply(Action.scala:464)
[error] play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:433)
[error] play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:432)
[error] play.api.mvc.Action$.invokeBlock(Action.scala:556)
[error] play.api.mvc.Action$.invokeBlock(Action.scala:555)
[error] play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:518)
[error] play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
[error] play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
[error] play.utils.Threads$.withContextClassLoader(Threads.scala:21)
[error] play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129)
[error] play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128)
[error] play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128)
[error] play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121)
[error] play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705)
[error] play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705)
[error] akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
[error] akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
[info]
[info]
[info] Total for specification ApplicationSpec
[info] Finished in 1 second, 273 ms
[info] 1 example, 0 failure, 1 error
[error] Error: Total 2, Failed 0, Errors 2, Passed 0
[error] Error during tests:
[error]         ApplicationSpec
[error]         IntegrationSpec
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 18 s, completed Jul 21, 2016 12:53:33 AM


 */
